### ISSUE TITLE
快照的增量问题

### ISSUE THREAD

**Issue by sunxiaozhi** [ca7dEm0n/elsticsearchTools#1]
如果是每天创建一个新的仓库的话，那这样快照都是全量的数据，到最后的不会占用很大磁盘空间吗？

**Comment by ca7dEm0n** [comment]
是不是全量得看你备份时的参数。 另外: 每天一个仓库这种方案不科学，现在在使用的脚本已经更改方式，稍后更新一波

**Comment by sunxiaozhi** [comment]
针对增量的数据的文件，可以单独压缩打包吗？或者通过快照名称来获得仓库下的每次快照的文件

**Comment by ca7dEm0n** [comment]
脚本利用的是快照功能噢，具体可以参考[官网](https://www.elastic.co/guide/cn/elasticsearch/guide/current/backing-up-your-cluster.html)
